// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzndxirdwafsbrnydarc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bmR4aXJkd2Fmc2JybnlkYXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ4NzksImV4cCI6MjA2NTQ3MDg3OX0.7xNHlFTnSH14Fj62t3bma5NlSS0UDpnxKN4mw1OJw9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);